### ISSUE TITLE
Alternative weather APIs?

### ISSUE THREAD

**Issue by nickforddesign** [dipu-bd/vue-weather-widget#17]
Since DarkSky has been acquired by apple, it is no longer possible to create an API key for the DarkSky API. https://blog.darksky.net/dark-sky-has-a-new-home/

Any thoughts on supporting alternative weather APIs?

 I'm using `vue-weather-widget` in a kind of fun side project, https://github.com/nickforddesign/vuebersicht, and this is one of the blockers to making it easy to set up Vuebersicht. If you are open to the idea but not motivated to implement, perhaps I can submit a PR?

**Comment by dipu-bd** [comment]
Yea. I am thinking about switching to https://openweathermap.org/api

But it has completely different set of icons. I love current skycons and want to keep them. 

If you can map the icons used by openweathermap to skycons, it would be a great help!

**Comment by nickforddesign** [comment]
Nice! I am pretty busy at the moment but might be able to take a stab at this on Sunday

**Comment by nickforddesign** [comment]
@dipu-bd

Okay so, looks like they don't map 1:1 but when looking at the OWM Icons themselves it's pretty straightforward.

Here's a mapping of all Skycon condition enums -> closest OpenWeatherMap Icon code:

```js
{
  CLEAR_DAY: ['01d'],
  CLEAR_NIGHT: ['01n'],
  CLOUDY: ['03d', '03n'],
  FOG: ['50d', '50n'],
  PARTLY_CLOUDY_DAY: ['02d', '04d',],
  PARTLY_CLOUDY_NIGHT: ['02n', '04n'],
  RAIN: ['09d', '09n', '10d', '10n', '11d', '11n'],
  SLEET: ['13d', '13n'],
  SNOW: ['13d', '13n'],
  WIND: ['50d', '50n']
}
```

I'd be happy to contribute a PR if you want, just let me know

**Comment by dipu-bd** [comment]
@nickforddesign Thanks a lot. Please send me a PR anytime you want.

**Comment by nickforddesign** [comment]
thank you for merging this! your changes look great too!
