### ISSUE TITLE
units is undefined (OWM)

### ISSUE THREAD

**Issue by nilsE** [dipu-bd/vue-weather-widget#19]
Would you mind to change this

 `&units=${units}` +

to

 `&units=${opts.units}` +

(vue-weather-widget/src/utils.js, Line 137)

otherwise the units param is "undefined" ;-(

Thanks!
Nils

**Comment by dipu-bd** [comment]
@nilsE thanks for reporting. I fixed it.

**Comment by nickforddesign** [comment]
my fault sorry, leftover from debugging
