### ISSUE TITLE
use-dark-sky-api prop docs

### ISSUE THREAD

**Issue by nickforddesign** [dipu-bd/vue-weather-widget#20]
Looks like the docs in the readme for the new prop `use-dark-sky-api` are wrong, default should be `false`, as it is in the code:

https://github.com/dipu-bd/vue-weather-widget#props
https://github.com/dipu-bd/vue-weather-widget/blob/master/src/script.js#L15

**Comment by dipu-bd** [comment]
oh right. forgot to change that
