### ISSUE TITLE
geocode call / mixed content issue

### ISSUE THREAD

**Issue by nilsE** [dipu-bd/vue-weather-widget#21]
The call to the geocoder (utils / geocode() - api.positionstack is always made to http://
This causes mixed content problems in ssl secured websites, i think better is the use of protocol less urls like:

`return fetch('//api.positionstack.com/v1/${apiType}?access_key=${apiKey}&query=${query}')`

**Comment by dipu-bd** [comment]
thanks for your suggestion. I will update it in the next release

**Comment by dipu-bd** [comment]
positionstack free tier does not allow https call. I have added a `positionstack-api` option to define your own api key
