### ISSUE TITLE
TypeError: Failed To Fetch

### ISSUE THREAD

**Issue by Yavieh** [dipu-bd/vue-weather-widget#35]
For me the widget is not working anymore.
Im using OpenWeatherMap

I always get the error "TypeError: Failed To Fetch"
Did someone else face that problem and found a solution?

**Comment by dipu-bd** [comment]
It is a issue with ip locator. Pass the coordinates and it should work.

I will fix this issue later

**Comment by Yavieh** [comment]
Thanks. Im using this for my Smart Home and its the best looking one i found :)

**Comment by Yavieh** [comment]
@dipu-bd Adding the coordiantes is working fine. 
My next problem is, that i now have https on my website.
I not get this error witch owm:
Error: (Api.Positionstack.Com) Access Restricted - Your Current Subscription Plan Does Not Support HTTPS Encryption.

Maybe you know what to do?

**Comment by dipu-bd** [comment]
PositionStack is being used for reverse geocoding. I did not add any feature to disable it. I will do that in the next version.

**Comment by dipu-bd** [comment]
Released v2.3.0 solving this issue
