### ISSUE TITLE
API key leak

### ISSUE THREAD

**Issue by janosdebugs** [dipu-bd/vue-weather-widget#42]
Hello,

The following locations seem to leak working API keys:

- https://github.com/dipu-bd/vue-weather-widget/blob/master/src/script.js#L87
- https://github.com/dipu-bd/vue-weather-widget/blob/master/src/script.js#L93

Credits to @bencurio for finding this.

**Comment by dipu-bd** [comment]
It is intentional. They were open just for demo purpose here.
