### ISSUE TITLE
Configure displayed days

### ISSUE THREAD

**Issue by Assisting** [dipu-bd/vue-weather-widget#7]
This is more of a feature request: could the widget be configurable to start from the current day onward, rather than displaying Monday to Monday? The feedback I've received using it is that it's hard to determine at a glance which weather is "today" out of the 8 being displayed.

I'd be happy to contribute and send in a pull request, but I think all the source code is minified.

**Comment by dipu-bd** [comment]
I got the the source from https://blog.darksky.net/forecast-embeds/ and have not changed it much. I know minified code is trouble. I created issue #13 for it. But I do not know when I am going to be able to work on it.

**Comment by dipu-bd** [comment]
done in v3
